allowBuilds:
  '@google/genai': false
  '@mongodb-js/zstd': false
  esbuild: true
  node-liblzma: false
  protobufjs: false
  sharp: false
  workerd: true
minimumReleaseAge: 10080
overrides:
  esbuild: 0.28.1
  valibot: 1.4.2
