import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";

const SCHEMAS = {
  activationContext: "activation-context.schema.json",
  invocationEnvelope: "invocation-envelope.schema.json",
  manifest: "manifest.schema.json",
  workspaceOperation: "workspace-operation.schema.json",
  workspaceRecord: "workspace-record.schema.json",
  workspaceResult: "workspace-result.schema.json",
} as const;

type RolePolicyInput = {
  id: string;
  lifecycle: string;
  capabilities: string[];
  sandbox_mode: string;
  model_profile: string;
  allowed_profiles: string[];
};

export function roleToolPolicySha256(role: RolePolicyInput): string {
  return createHash("sha256")
    .update(
      JSON.stringify({
        capabilities: [...role.capabilities].sort(),
        lifecycle: role.lifecycle,
        role: role.id,
        sandbox_mode: role.sandbox_mode,
      }),
    )
    .digest("hex");
}

export function generateAgentValidatorsSource(sourceDir: string): string {
  const schemaDir = resolve(sourceDir, "schemas");
  const ajv = new Ajv2020({
    allErrors: true,
    code: { source: true },
    strict: true,
  });
  const refs: Record<string, string> = {};
  for (const [exportName, filename] of Object.entries(SCHEMAS)) {
    const schema = JSON.parse(
      readFileSync(join(schemaDir, filename), "utf-8"),
    ) as { $id: string };
    ajv.addSchema(schema, schema.$id);
    refs[exportName] = schema.$id;
  }
  return [
    "// Generated by scripts/ax/generate-agent-validators.ts. Do not edit.",
    standaloneCode(ajv, refs)
      .replaceAll(
        'require("ajv/dist/runtime/ucs2length")',
        'require("./ucs2length.cjs")',
      )
      .replaceAll(
        'require("ajv/dist/runtime/equal")',
        'require("./equal.cjs")',
      ),
    "",
  ].join("\n");
}

export function generateAgentRolePoliciesSource(sourceDir: string): string {
  const manifest = JSON.parse(
    readFileSync(resolve(sourceDir, "manifest.json"), "utf-8"),
  ) as {
    prompt_contract_version: string;
    roles: RolePolicyInput[];
  };
  const roles = Object.fromEntries(
    [...manifest.roles]
      .sort((left, right) => left.id.localeCompare(right.id))
      .map((role) => [
        role.id,
        {
          allowed_profiles: [...role.allowed_profiles].sort(),
          capabilities: [...role.capabilities].sort(),
          lifecycle: role.lifecycle,
          model_profile: role.model_profile,
          sandbox_mode: role.sandbox_mode,
          tool_policy_sha256: roleToolPolicySha256(role),
        },
      ]),
  );
  return `${JSON.stringify(
    {
      prompt_contract_version: manifest.prompt_contract_version,
      roles,
    },
    null,
    2,
  )}\n`;
}
